config/routes.rb
Rails.application.routes.draw do
  resources :challenges 
  devise_for :users
 # devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'article/index'
  root to: 'challenges#new'
  get "sorted"=>"challenges#sorted"
  resources :challenges do
    member do
      put "upvote", to: "challenges#upvote"
    end  
  end
    
  resources :challenges do
    member do
      get "follow" => "challenges#follow"
    
    end
  end
  namespace :api do
    namespace :v1 do
     resources :challenges
    end     
  end
  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def index
  end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/article/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small bg-primary text-white " style="padding:30px; position: fixed;
    bottom: 0;
    width: 100%;">

  <!-- Footer Links -->


  <!-- Copyright -->
  <div class="footer-copyright text-center ">© 2020 Copyright:
    <a href="#" class="text-white"> Hackathon.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/article/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary justify-content-center"  style="padding:20px;">
  
 

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" style="list-style:none;">

      <li style="margin-left:100px;">
      <h1 class="text-whitecs" >Hackathon</h1>
      </li>
    <li style="margin-left:1000px;"><h3>
    <% if user_signed_in?%>

      <%= link_to "Home", challenges_path, class:'nav-link text-white', style:"color:white;"%>

<%end%> </h3>
</li>   

      <% if user_signed_in?%>



          <li class="nav-item " id="applicants-nav-index" style="margin-left:100px;">
              <h3>  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:'nav-link nav-text', style:"color:white;" %></h3>
              </li>

      <%else%>

          <li class="nav-item " id="applicants-nav-index" style="margin-left:100px">
            <h3>    <%= link_to "Sign Up",new_user_registration_path, class:'nav-link nav-text', style:"color:white;" %></h3>
              </li>
          <li class="nav-item " id="applicants-nav-index"style="margin-left:100px;">
              <h3>  <%= link_to "Sign In", new_user_session_path, class:'nav-link nav-text' , style:"color:white;"%></h3>
              </li>


      <%end%>



    </ul>
    
  </div>
</nav>

app/views/article/index.html.erb
<h1>Article#index</h1>
<p>Find me in app/views/article/index.html.erb</p>