config/routes.rb
Rails.application.routes.draw do
  resources :challenges 
  devise_for :users
 # devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'article/index'
  root to: 'challenges#new'
  get "sorted"=>"challenges#sorted"
  resources :challenges do
    member do
      put "upvote", to: "challenges#upvote"
    end  
  end
    
  resources :challenges do
    member do
      get "follow" => "challenges#follow"
    
    end
  end
  namespace :api do
    namespace :v1 do
     resources :challenges
    end     
  end
  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/challenge.rb
class Challenge < ApplicationRecord
    acts_as_votable
    acts_as_followable
    belongs_to :user  
    validates :title, presence: true,uniqueness: true, length: {minimum:4,maximum:20}
    validates :description, presence: true, length: {minimum:4,maximum:100}
    def self.search(search)
        if search
          where('title LIKE ?', "%#{search}%")
        
            
        else
        all  
        
        end
      end
end

app/controllers/api/v1/challenges_controller.rb
class Api::V1::ChallengesController < ApplicationController

  def index
    @challenges = Challenge.all
    render json: { status: 'SUCCESS', message: 'Loaded challenges', data:@challenges}, status: :ok
  end 

  def create
    @challenge = Challenge.new(challenge_params)

    if @challenge.save
      render json: { status: 'SUCCESS', message: 'Saved challenge', data:@challenge}, status: :ok
    else
      render json: { status: 'ERROR', message: 'challenge not Saved', data:@challenge.errors }, status: :unprocessable_entity
    end
  end

  def update
    @challenge = Challenge.find(params[:id])
    if @challenge.update_attributes(challenge_params)
      render json: { status: 'SUCCESS', message: 'Updated challenge', data:@challenge}, status: :ok
    else
      render json: { status: 'ERROR', message: 'challenge not Updated', data:@challenge.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @challenge = Challenge.find(params[:id])
    @challenge.destroy
    render json: { status: 'SUCCESS', message: 'Deleted challenge', data:@challenge}, status: :ok
  end

  def show
    @challenge = Challenge.find(params[:id])
    render json: { status: 'SUCCESS', message: 'Loaded challenge', data:@challenge}, status: :ok
  end

  private

  def challenge_params
    params.require(:challenge).permit(:title, :description, :tag, :user_id)
  end
  
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  respond_to :js, :html, :json
  before_action :set_challenge, only: %i[ show edit update destroy upvote follow current_user]
 # before_action :new_index, only: %i[ index new ]
  before_action :authenticate_user!, except: %i[show search]
  before_action :correct_user, only: %i[edit update destroy]
  helper_method :sort_column, :sort_direction


  # GET /challenges or /challenges.json
  def index
    @challenges = Challenge.all.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    @challenge = current_user.challenges.build

   # sorted = @challenges.sort_by &:tags
  end
  
  # GET /challenges/1 or /challenges/1.json
  def show
  end


  # GET /challenges/new
  def new
    @challenges = Challenge.all.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    @challenge = current_user.challenges.build

    
  end

  # GET /challenges/1/edit
  def edit
    unless current_user 
      redirect_to challenge_path, :alert => "Restricted area" 
    end
  end

  # POST /challenges or /challenges.json
  def create
   # @challenge = Challenge.new(challenge_params)
   @challenges = Challenge.all

    @challenge = current_user.challenges.build(challenge_params)
    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: "Challenge was successfully created." }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1 or /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: "Challenge was successfully updated." }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1 or /challenges/1.json
  def destroy
    unless current_user 
      redirect_to challenge_path, :alert => "Restricted area" 
    end
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: "Challenge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @challenge=current_user.challenges.find_by(id: params[:id])
    redirect_to challenges_path, notice: "Not authorize to edit" if @challenge.nil?
  end  
  def upvote
    @challenge = Challenge.find(params[:id])
    @challenge.upvote_by current_user
    redirect_to challenges_path 
  end
  def follow
    @challenge = Challenge.find(params[:id])
    
    current_user.follow(@challenge)
    redirect_to challenges_path 
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end
    # def new_index
    #   @challenges = Challenge.all.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    #   @challenge = current_user.challenges.build

    # end  
    def sort_column
      Challenge.column_names.include?(params[:sort]) ? params[:sort] : "title"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    # Only allow a list of trusted parameters through.
    def challenge_params
      params.require(:challenge).permit(:title, :description, :tags, :user_id)
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_add.html.erb
<p id="notice"><%= notice %></p>

<h1>Challenges</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% challenges.each do |challenge| %>
      <tr>
        <td><%= challenge.title %></td>
        <td><%= challenge.description %></td>
        <td><%= challenge.tags %></td>
        <td><%= link_to 'Show', challenge %></td>
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Challenge', new_challenge_path %>

app/views/challenges/_form.html.erb
<%= form_with(model: challenge, local: true) do |form| %>
  <% if challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
        <% challenge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<table class="table ">
  <thead class="bg-dark text-white">
    <tr>
    
      <th scope="col" class="text-center py-3"><%= form.label :title %></th>
      <th scope="col" class="text-center"><%= form.label :description %></th>
      <th scope="col" class="text-center"> <%= form.label :tags %> </th>
      <th colspan=1></th>
    </tr>
  </thead>
  <tbody >
    <tr >
    
      <td class="text-center "style="padding:50px;"><%= form.text_field :title %></td>
      <td class="text-center" style="padding:50px;"><%= form.text_field :description %></td>
      

      <td class="text-center" style="padding:50px;"> <%= form.select :tags, [ 'Array','Bitmasking','BST','DP','Graph','Greedy','Recursion','Searching','Sorting','String','Tree'  ], :prompt => 'Select One' %></td>
        <div class="field">
   </div>

       <div class="actions">
   <td style="padding:50px;"> <%= form.submit class:"btn btn-sm bg-primary text-white"%></td>
  </div>
    </tr>
    
  </tbody>
</table>
  

<% end %>

app/views/challenges/edit.html.erb
<div class="container">
<br>
<br>
<br>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>
<br>
<br><br><br><br><br><br><br>

<br><br><br><br>
<br>
<br><br><br><br><br><br><br>

<br><br><br><br>
</div>

app/views/challenges/index.html.erb
<div class="container">



  <div class=" row bg-primary text-white">
   <div class="col-sm-8 mt-2">  <h3>Challenges</h3></div>
     <div class="col-sm-4 mt-3">
<%= form_tag challenges_path, :method => 'get' do %>
  <p style="padding-top:15px;">
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil , class:" btn btn-sm bg-dark " ,style:"color:black"%>
  </p>
  

<% end %>
</div>
  </div>
  <div class="">
  <table class="table " id="my-table">
  <thead class="">
    <tr class="bg-dark text-white text-center">
     <th scope="col"></th>
        <th scope="col" class="text-white"><%= sortable "title" %></th>
      <th scope="col" class="text-white"><%= sortable "description" %></th>
      <th scope="col" class="text-white"><%= sortable "tags"%></th>
      <th scope="col" class="text-white"><%= sortable "created_at"%></th>

      <th scope="col">Created by</th>
      
      <th scope="col"> Upvote</th>
      
      <th scope="col">#</th>
      <th scope="col">Colab</th>
      <th scope="col">
      Colaborators list
      </th>
      <th scope="col">#</th>
    </tr>
  </thead>

  <tbody>
  <br>
  <% @var=1%>
    <% @challenges.each do |challenge| %>
      <tr class="text-center">
       <th scope="row"><%=@var%></th>
       <%@var=@var+1%>
       
        <td><%= challenge.title.capitalize  %></td>
        <td><%= challenge.description.capitalize  %></td>
        <td><%= challenge.tags  %></td>
          <%@u=User.find_by(id: challenge.user_id)%>
  <td><%= challenge.created_at.strftime("%Y-%m-%d") %></td>

  <td><%= @u.employee_id %></td>
        
        
        <td>
        <%= challenge.get_upvotes.size%>
        </td>
        <td><%if current_user.id!=challenge.user_id%>
        <% if !current_user.voted_up_on? challenge %>
        <%=button_to  "", upvote_challenge_path(challenge), method: :put , class:"fa fa-plus",style:'font-size:30px;'%>
        <%else%>
        <p class="text-success"> <i class="fa fa-check-square-o" style='font-size:30px;'></i></p>
        <%end%>
        <%else%>
    <a class="text-danger"><i class='fa fa-ban' style='font-size:30px;'></i></a>
        <%end%></td>
        <td> 
        <%if current_user.id!=challenge.user_id%>
        <% if !challenge.followed_by?(current_user) %>
    <%= link_to "", follow_challenge_path(challenge), class: " fa fa-handshake-o text-primary",style:'font-size:30px;'%>
    <%else%>
    <p class="text-success"> <i class="fa fa-check-circle" style='font-size:30px;'></i></p>
  <% end %></td>
  <%else%>

 <a class="text-danger"><i class='fa fa-ban' style='font-size:30px;'></i></a>
    
  <%end%>
   <td>
 <% allfollows = challenge.followers %>
<%allfollows.each do |item|%>
<%=item.employee_id%>
<br>
<%end%>
</td>
        <td><%= link_to 'Show', challenge,class:"btn btn-sm bg-dark text-white" %></td>
        <% link_to 'Edit', edit_challenge_path(challenge) %>
      <td>  <% link_to 'Destroy', challenges_path(challenge), method: :delete, data: { confirm: 'Are you sure?' } %></td>
     
      </tr>

  </tbody>
    <% end %>
    

</table>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @challenges %>
  </div>
</div>

<br>
<br>
<br>
<br>
</div>

app/views/challenges/like.js.erb
$('.preached-btn').on('ajax:success', function() {
$(this).parent().parent().find('.like_count')
.html('<%= @post.get_likes.size %> &#128591');
$(this).closest('.preached-btn').html( 'Preach');
});
$('.preach-btn').on('ajax: success', function() {
$(this).parent().parent().find('.like_count')
.html('<%= @post.get_likes.size %> &#128591');
$(this).closest('.preach-btn').html( 'Preached');
});

app/views/challenges/new.html.erb
<div class="container">



  <div class=" row bg-primary text-white">
   <div class="col-sm-8 mt-2">  <h3>Challenges</h3></div>
     <div class="col-sm-4 mt-3">
<%= form_tag challenges_path, :method => 'get' do %>
  <p style="padding-top:15px;">
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil , class:" btn btn-sm bg-dark ",style:"color:black"%>
  </p>
  

<% end %>
</div>
  </div>
  <div class="">
  <table class="table " id="my-table">
  <thead class="">
    <tr class="bg-dark text-white text-center">
     <th scope="col"></th>
        <th scope="col" class="text-white"><%= sortable "title" %></th>
      <th scope="col" class="text-white"><%= sortable "description" %></th>
      <th scope="col" class="text-white"><%= sortable "tags"%></th>
      <th scope="col" class="text-white"><%= sortable "created_at"%></th>

      <th scope="col">Created by</th>
      
      <th scope="col"> Upvote</th>
      
      <th scope="col">#</th>
      <th scope="col">Colab</th>
      <th scope="col">
      Colaborators list
      </th>
      <th scope="col">#</th>
      <th scope="col">#</th>
    </tr>
  </thead>

  <tbody>
  <br>
  <% @var=1%>
    <% @challenges.each do |challenge| %>
      <tr class="text-center">
       <th scope="row"><%=@var%></th>
       <%@var=@var+1%>
       
        <td><%= challenge.title.capitalize  %></td>
        <td><%= challenge.description.capitalize  %></td>
        <td><%= challenge.tags  %></td>
          <%@u=User.find_by(id: challenge.user_id)%>
  <td><%= challenge.created_at.strftime("%Y-%m-%d") %></td>

  <td><%= @u.employee_id %></td>
        
        
        <td>
        <%= challenge.get_upvotes.size%>
        </td>
        <td><%if current_user.id!=challenge.user_id%>
        <% if !current_user.voted_up_on? challenge %>
        <%=button_to  "", upvote_challenge_path(challenge), method: :put , class:"fa fa-plus",style:'font-size:30px;'%>
        <%else%>
        <p class="text-success"> <i class="fa fa-check-square-o" style='font-size:30px;'></i></p>
        <%end%>
        <%else%>
    <a class="text-danger"><i class='fa fa-ban' style='font-size:30px;'></i></a>
        <%end%></td>
        <td> 
        <%if current_user.id!=challenge.user_id%>
        <% if !challenge.followed_by?(current_user) %>
    <%= link_to "", follow_challenge_path(challenge), class: " fa fa-handshake-o text-primary",style:'font-size:30px;'%>
    <%else%>
    <p class="text-success"> <i class="fa fa-check-circle" style='font-size:30px;'></i></p>
  <% end %></td>
  <%else%>

 <a class="text-danger"><i class='fa fa-ban' style='font-size:30px;'></i></a>
    
  <%end%>
   <td>
 <% allfollows = challenge.followers %>
<%allfollows.each do |item|%>
<%=item.employee_id%>
<br>
<%end%>
</td>
        <td><%= link_to 'Show', challenge,class:"btn btn-sm bg-dark text-white" %></td>
        <% link_to 'Edit', edit_challenge_path(challenge) %>
      <td>  <%= link_to 'Destroy', challenges_path(challenge), method: :delete, data: { confirm: 'Are you sure?' } %></td>
     
      
      </tr>

  </tbody>
    <% end %>
    

</table>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @challenges %>
  </div>
</div>

<br>
<br>
<br>
<br>
</div>

app/views/challenges/show.html.erb
<div class="container">
<div class="card text-center">
  <div class="card-header">
    <h3>Challenge<h3>
  </div>
  <div class="card-body">
   <p>
  <strong>Title:</strong>
  <%= @challenge.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @challenge.description %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @challenge.tags %>
</p>

  </div>
  <div class="card-footer text-muted">
<p>
<h4>Collaborator list</h4>
<hr>
 <% allfollows = @challenge.followers %>
<%allfollows.each do |item|%>
<%=item.employee_id%>
<br>
<%end%>

</p>
  </div>

<%= link_to 'Edit', edit_challenge_path(@challenge) %> <br>
<%= link_to 'Back', challenges_path %>
<%= button_to 'Destroy', challenge_path(@challenge), method: :delete %>
 
 </div>


</div>
<br>
<br><br><br><br><br><br><br>
<br><br><br><br><br><br><br>
<br><br><br>

app/views/challenges/sorted.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<%= render 'form'%>
<br>
<br>
<br>
<hr>
<div class="card">
  <div class="card-header">
     <h1>Challenges</h1>

     <%= link_to "Normal" , challenges_path ,class:"btn-primary"%>
  </div>
  <div class="card-body">
  <table class="table table-bordered">
  <thead>
    <tr>
     <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Tags</th>
      <th scope="col">Created by</th>
      <th scope="col">created at</th>
      <th scope="col">Upvote</th>
      <th scope="col">#</th>
      <th scope="col">Colab</th>
      <th colspan="3"></th>
      <th scope="col">List</th>
    </tr>
  </thead>

  <tbody>
  <% @var=1%>
    <% @challenges.each do |challenge| %>
      <tr>
       <th scope="row"><%=@var%></th>
       <%@var=@var+1%>
        <td><%= challenge.title %></td>
        <td><%= challenge.description %></td>
        <td><%= challenge.tags %></td>
          <%@u=User.find_by(id: challenge.user_id)%>
  <td><%= @u.employee_id %></td>
  <td><%= challenge.created_at %></td>
        
        
        <td>
        <%= challenge.get_upvotes.size%>
        </td>
        <td><%if current_user.id!=challenge.user_id%>
        <%= link_to  "+", upvote_challenge_path(challenge), method: :put %>
        <%else%>
    <button> NA</button>
        <%end%></td>
        <td> 
        <%if current_user.id!=challenge.user_id%>
        <% if !challenge.followed_by?(current_user) %>
    <%= link_to "Colaborate", follow_challenge_path(challenge), class: "btn btn-success btn-outline btn-sm"%>
    <%else%>
    <button> colaborated</button>
  <% end %></td>
  <%else%>
  <button> NA</button>
  <%end%>
        <td><%= link_to 'Show', challenge %></td>
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 <td>
 <% allfollows = challenge.followers %>
<%allfollows.each do |item|%>
<%=item.employee_id%>
<br>
<%end%>
</td>     
      </tr>

  </tbody>
    <% end %>
    

</table>

  </div>
</div>


<br>

<%= link_to 'New Challenge', new_challenge_path %>
</div>